# Generated by Django 5.0.1 on 2024-01-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200, verbose_name='Название аккаунта')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона аккаунта')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_account', to='bot.account', verbose_name='Привязанный аккаунт')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(to='bot.group', verbose_name='Название группы/групп'),
        ),
    ]
