# Generated by Django 5.0.1 on 2024-01-24 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_url',
            field=models.TextField(null=True, verbose_name='Ссылка на чат'),
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, to='bot.group', verbose_name='Название группы/групп (Необязательное поле, можно добавить из группы)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_accounts', to='bot.account', verbose_name='Привязанный аккаунт'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=200, verbose_name='Название группы ватсап'),
        ),
        migrations.CreateModel(
            name='RSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_name', models.CharField(max_length=200, verbose_name='Название RSS ленты')),
                ('rss_url', models.TextField(verbose_name='Ссылка на RSS ленту')),
                ('group_rss', models.ManyToManyField(blank=True, to='bot.group', verbose_name='Группы связанные с RSS лентой (Необязательное поле, можно добавить из группы)')),
            ],
            options={
                'verbose_name': 'RSS лента',
                'verbose_name_plural': 'RSS ленты',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='rss_for_group',
            field=models.ManyToManyField(to='bot.rss', verbose_name='RSS ленты связанные с группой'),
        ),
    ]
