# Generated by Django 5.0.1 on 2024-01-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_group_group_url_alter_account_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, to='bot.group', verbose_name='Название группы/ групп<br>(Cоздается, редактируется и удаляется в разделе Группы'),
        ),
        migrations.AlterField(
            model_name='rss',
            name='group_rss',
            field=models.ManyToManyField(blank=True, to='bot.group', verbose_name='Группы связанные с RSS лентой<br>(Cоздается, редактируется и удаляется в разделе Группы'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=300, verbose_name='Название новости')),
                ('created_at', models.DateTimeField(verbose_name='Дата отправки новости')),
                ('post_to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group', verbose_name='Группа, куда отправилась новость')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.account', verbose_name='Аккаунт отправителя новости')),
            ],
            options={
                'verbose_name': 'Новостной пост',
                'verbose_name_plural': 'Новостные посты',
                'ordering': ['-id'],
            },
        ),
    ]
