# Generated by Django 5.0.1 on 2024-01-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_url',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.TextField(null=True, verbose_name='ID группы'),
        ),
    ]
